// ============================================================
// Build: renders src/pages/*.js into dist/ as plain static HTML
// and copies the assets. No runtime framework, no client-side
// rendering — every page ships complete.
//
//   npm run build
// ============================================================
import fs from 'node:fs';
import path from 'node:path';
import { SITE_URL, BASE_PATH, PROTOTYPE } from './src/layout.js';
import { analytics } from './src/data/analytics.js';
import * as data from './src/data/site-data.js';
import { REDIRECTS } from './src/data/redirects.js';

import home from './src/pages/home.js';
import joinACourse from './src/pages/join-a-course.js';
import bringAGroup from './src/pages/bring-a-group.js';
import planAMobility from './src/pages/plan-a-mobility.js';
import dates from './src/pages/dates.js';
import yourWeek from './src/pages/your-week.js';
import barcelona from './src/pages/barcelona.js';
import about from './src/pages/about.js';
import contact from './src/pages/contact.js';
import privacy from './src/pages/privacy.js';
import cookies from './src/pages/cookies.js';
import notFound from './src/pages/not-found.js';

const DIST = 'dist';

// route → renderer. The route is also the canonical URL.
export const PAGES = {
  '/': home,
  '/join-a-course/': joinACourse,
  '/bring-a-group/': bringAGroup,
  '/plan-a-mobility/': planAMobility,
  '/dates/': dates,
  '/your-week/': yourWeek,
  '/barcelona/': barcelona,
  '/about/': about,
  '/contact/': contact,
  '/privacy/': privacy,
  '/cookies/': cookies,
  '/404.html': notFound,
};

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dst);
    else if (entry.name !== 'manifest.json') fs.copyFileSync(src, dst);
  }
}

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

let count = 0;
// Root-relative links become BASE_PATH-relative ones. Absolute URLs
// (http…) and fragment-only links are left alone. srcset holds a
// comma-separated list, so each candidate in it needs the prefix too.
const withBase = (html) => {
  if (!BASE_PATH) return html;
  return html
    .replace(/(href|src)="\/(?!\/)/g, `$1="${BASE_PATH}/`)
    .replace(/srcset="([^"]+)"/g, (_, list) => 'srcset="' + list
      .split(',')
      .map((candidate) => candidate.replace(/^(\s*)\/(?!\/)/, `$1${BASE_PATH}/`))
      .join(',') + '"');
};

const BANNER = '<!-- Generated by build.mjs from src/. Do not edit; run `npm run build`. -->\n';

for (const [route, render] of Object.entries(PAGES)) {
  const file = route.endsWith('.html')
    ? path.join(DIST, route.slice(1))
    : path.join(DIST, route.slice(1), 'index.html');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, BANNER + withBase(render()));
  count++;
}

copyDir('src/assets', path.join(DIST, 'assets'));

// robots.txt and a sitemap, generated from the same route list.
const urls = Object.keys(PAGES).filter((r) => !r.endsWith('.html'));
fs.writeFileSync(path.join(DIST, 'robots.txt'), PROTOTYPE
  ? `# Prototype build — not the published site.\nUser-agent: *\nDisallow: /\n`
  : `User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`);
fs.writeFileSync(path.join(DIST, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls.map((u) => `  <url><loc>${SITE_URL}${u}</loc></url>`).join('\n') +
  `\n</urlset>\n`);

// A static host has no redirect rules, so the prototype ships a small
// redirecting page at each legacy path instead. A real deploy uses the
// server's redirect map and does not need these.
if (PROTOTYPE) {
  let stubs = 0;
  for (const [from, to] of Object.entries(REDIRECTS)) {
    if (!from.endsWith('/')) continue;           // /home and /home/ are the same page
    const target = BASE_PATH + to;
    const file = path.join(DIST, from.slice(1), 'index.html');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Moved — Erasmus in Barcelona</title>
<meta name="robots" content="noindex, follow">
<link rel="canonical" href="${SITE_URL}${to.split('#')[0]}">
<meta http-equiv="refresh" content="0; url=${target}">
</head>
<body>
<p>This page has moved to <a href="${target}">${target}</a>.</p>
</body>
</html>
`);
    stubs++;
  }
  console.log(`${stubs} legacy paths redirect to their new page`);
}

// GitHub Pages runs Jekyll over a branch unless told not to.
fs.writeFileSync(path.join(DIST, '.nojekyll'), '');

console.log(`${count} pages → ${DIST}/${BASE_PATH ? ` (base path ${BASE_PATH})` : ''}${PROTOTYPE ? ' [prototype: noindex]' : ''}`);
console.log(`${urls.length} URLs in sitemap.xml · ${data.dates.length} course weeks · ` +
  `${data.courseAreas.length} subject areas`);
console.log(analytics.websiteId
  ? `analytics: ${analytics.provider} ${analytics.region}, website ${analytics.websiteId.slice(0, 8)}…, `
    + `reporting to ${new URL(analytics.collector).host} only from ${analytics.domains}`
  : 'analytics: no tracker in this build');
